baseURL = "https://blog.cfw4.tokyo"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "あんなことやこんなこと"
theme = "rokkaku"
hasCJKLanguage = true
pygmentsCodeFences = true
pygmentsUseClasses = true

copyright = "&copy; 2014-2021 naniwastrongboy"
disqusShortname = "annakotoyakonnakoto"
googleAnalytics = "UA-58961735-4"
summarylength = 70

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "naniwastrongboy"

[params]
  description = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
  author = "aki.f"
  twitter = "naniwastrongboy"
  useIcon = true
  useTwitterCard = true
  match = true
  paginationSinglePost = true
  style = "dark"
  readMore = false
  shareTo = ["Twitter", "Hatena", "Pocket"]
showFooterCredits = true

[languages]
[languages.ja]
  dateFormat = "2006年1月2日"


[menu]

  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/wordpress"
    weight = 2

