baseURL = "/"
languageCode = "ja-jp"
title = "あんなことやこんなこと"
theme = "hugo-theme-terminal"
paginate = 20

[params]
  contentTypeName = "wordpress"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  [languages]
    [languages.en]
    title = "あんなことやこんなこと"
    subtitle = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
    owner = "naniwa"
    keywords = ""
    copyright = "(c) 2014-2021 naniwa"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    [languages.en.params.logo]
      logoText = "あんなことやこんなこと"
      logoHomeLink = "/"
