baseurl: "https://blog.cfw4.tokyo"
title: "あんなことやこんなこと"
languageCode: "ja"
#defaultContentLanguage = "ja"
theme: "github-style"
hasCJKLanguage: true
pygmentsCodeFences: true
pygmentsUseClasses: true
googleAnalytics: "UA-58961735-4"
copyright: "&copy; 2014-2021 naniwastrongboy"
disqusShortname: "annakotoyakonnakoto"
summarylength: 70

taxonomies:
  tag: "tags"
  archive: "archives"
params:
  limitNumberOfLatests: 100
  author: "naniwa"
  description: "In solitude, where we are least alone."
  twitter: "naniwastrongboy"
  rss: true
  location: "Japanese"
