baseURL = "https://blog.cfw4.tokyo"
languageCode = "ja-jp"
defaultContentLanguage = "ja-jp"
title = "あんなことやこんなこと"
theme = "anubis"
hasCJKLanguage = true

copyright = "&copy; 2014-2021 aki.f"
disqusShortname = "annakotoyakonnakoto"
googleAnalytics = "UA-58961735-4"
summarylength = 50

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "aki.f"

[params]
  description = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
  author = "aki.f"
  dateFormat= "2006-01-02"
  paginationSinglePost = true
  style = "dark"
  readMore = false

  utterancesRepo = ""  # mandatory
  utterancesTheme = "" # optional
  utterancesIssue = "" # optional
  utterancesLabel = "" # optional

[menu]

  [[menu.main]]
    identifier = "top"
    name = "Top"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/wordpress/"
    weight = 2

