baseURL = "https://blog.cfw4.tokyo/"
languageCode = "ja"
title = "あんなことやこんなこと"
theme = "hugo-theme-terminal"
paginate = 20

disqusShortname = "annakotoyakonnakoto"
googleAnalytics = "UA-58961735-2"
hasCJKLanguage = true
pygmentsCodeFences = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  [languages]
    [languages.ja]
    title = "あんなことやこんなこと"
    subtitle = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
    owner = "naniwa"
    keywords = ""
    copyright = "(c) 2014-2021 naniwa"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    [languages.ja.params.logo]
      logoText = "あんなことやこんなこと"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "wordpress"
        name = "過去の記事"
        url = "/wordpress"
      [[languages.ja.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
