baseurl: "https://blog.cfw4.tokyo"
title: "あんなことやこんなこと"
languageCode: "ja-jp"
#defaultContentLanguage = "ja"
theme: "rokkaku"
hasCJKLanguage: true
pygmentsCodeFences: true
pygmentsUseClasses: true
googleAnalytics: "UA-58961735-4"
copyright: "&copy; 2014-2021 naniwastrongboy"
disqusShortname: "annakotoyakonnakoto"
summarylength: 70

taxonomies:
  tag: "tags"
  archive: "archives"
params:
  limitNumberOfLatests: 100

