baseURL = "https://blog.cfw4.tokyo"
languageCode = "ja"
defaultContentLanguage = "ja-jp"
title = "あんなことやこんなこと"
theme = "theer"
hasCJKLanguage = true
pygmentsCodeFences = true
pygmentsUseClasses = true

copyright = "&copy; 2014-2021 aki.f"
disqusShortname = "annakotoyakonnakoto"
googleAnalytics = "UA-58961735-4"
summarylength = 70

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "aki.f"

[params]
  description = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
  author = "aki.f"
  twitter = "naniwastrongboy"
  useIcon = true
  useTwitterCard = true
  match = true
  dateFormat= "2006-01-02"
  paginationSinglePost = true
  style = "dark"
  readMore = false
  shareTo = ["Twitter", "Hatena", "Pocket"]
showFooterCredits = true


[menu]

  [[menu.main]]
    identifier = "top"
    name = "Top"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/wordpress/"
    weight = 2

