baseURL = "https://blog.cfw4.tokyo/"
languageCode = "ja-jp"
defaultContentLanguage = "ja-jp"
title = "あんなことやこんなこと"
theme = "Memorandum"
hasCJKLanguage = true

copyright = "&copy; 2014-2021 aki.f"
disqusShortname = "annakotoyakonnakoto"
googleAnalytics = "UA-58961735-2"
summarylength = 50

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "基本的に書いたらほったらかし。感想をコメントでくれたらうれしいです。Since 2014. "
keywords = []
author = "aki.f"
profile = "自己紹介を書いて"
displayauthor = false
DateForm = "2006-01-02"

[params.highlight]
theme = "monokai-sublime"

[[params.social]]
url = "https://github.com/"
fa_icon_class = "fab fa-github"

[[params.social]]
url = "https://twitter.com/"
fa_icon_class = "fab fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon_class = "fas fa-rss"

